version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: weekly
    time: "06:00"
    timezone: America/Sao_Paulo
  open-pull-requests-limit: 10
  target-branch: dev
  reviewers:
  - ricardokazu