name: YAPF Formatter

on:
  push:
    branches-ignore:
      - "master"
    tags-ignore:
      - v*
      - v*.*
      - v*.*.*
    paths:
      - "**.py"

jobs:
  build:
    name: YAPF Formatter
    runs-on: ubuntu-latest

    steps:
      - name: checkout repo
        uses: actions/checkout@v2.3.4
        with:
          repository: ${{ github.repository }}
          token: ${{ github.token }}

      # https://github.com/diegovalenzuelaiturra/yapf-action
      - name: YAPF Formatter
        uses: diegovalenzuelaiturra/yapf-action@master
        with:
          args: . --verbose --recursive --in-place --parallel

      # https://github.com/myint/autoflake
      - name: Install autoflake
        run: |
          python -m pip install --upgrade autoflake

      - name: Removing unused variables and imports
        run: |
          autoflake jai/tests/ --remove-unused-variables --remove-all-unused-imports --ignore-init-module-imports --recursive --in-place

      # https://github.com/PyCQA/isort
      # https://github.com/isort/isort-action
      - uses: isort/isort-action@master
        with:
            sortPaths: "jai/"
            configuration: "--atomic"
            

      - name: action metadata
        run: |
          echo -e "action     : ${{ github.action }}"
          echo -e "actor      : ${{ github.actor }}"
          echo -e "event_name : ${{ github.event_name }}"
          echo -e "job        : ${{ github.job }}"
          echo -e "ref        : ${{ github.ref }}"
          echo -e" repository : ${{ github.repository }}"
          echo -e "run_id     : ${{ github.run_id }}"
          echo -e "sha        : ${{ github.sha }}"
          echo -e "workflow   : ${{ github.workflow }}"
          echo -e "workspace  : ${{ github.workspace }}"

      - name: config github
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

      - name: add changes
        run: |
          git add .

      - name: commit changes
        run: |
          git commit -m "Automation: YAPF Formatter" --all | exit 0

      # NOTE : only push changes when the source branch is being pushed to main (target branch)
      - name: push changes
        if: github.ref != 'refs/heads/main' && startsWith( github.ref, 'refs/heads/' )
        run: |
          git push
